name: 'Master - PR Close'
on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  merge_pr:
    name: 'PR Merged'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_NAME }}"
      - name: Apply version bump (major)
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: npm version major
      - name: Apply version bump (minor)
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: npm version minor
      - name: Apply version bump (patch)
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: npm version patch
        # update version then push to master force
      - name: Git push version bump
        # --follow-tags will be create annotated tag which means includes message in git show
        run: git push origin dev --follow-tags --force
      - id: set-version
        name: Output version change
        # get package.json version, but only effect after Node16+
        run: npm pkg get version