name: 'Master - PR Label Checker'
on:
  pull_request:
    branches:
      - master
    types:
      - reopened
      - labeled
      - unlabeled
jobs:
  check_labels:
    name: 'Check PR Labels'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mheap/github-action-required-labels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          # exectly set one of major/minor/patch labels
          mode: exactly
          count: 1
          labels: 'major, minor, patch'