name: readme Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm
      - run: pnpm i
      - run: npm run readme
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update readme"
