# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  # allow to run manually
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v2
      # use pnpm and set version
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.0
      # set node versiona and cache
      - uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 16.x
          cache: pnpm
      - run: npm run init
      - run: npm run readme
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}